version: "3.8"

services:
  postgres:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgresql
      POSTGRES_USER: postgres
      POSTGRES_DB: eMall
    ports:
      - 5433:5432
    networks:
      - shared-networks
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
      - ./db/db_preparation.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    container_name: eMall_server
    restart: unless-stopped
    image: emall-server-prod:1.0.0
    build:
      context: server
      target: production
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 5000:5000
    networks:
      - shared-networks
    depends_on:
      - postgres
    env_file:
      - .env

  client:
    container_name: eMall_client
    restart: unless-stopped
    image: emall-client-prod:1.0.0
    build:
      context: client
      target: production
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    networks:
      - shared-networks
    depends_on:
      - server

  simulator:
    container_name: eMall_cpsimulator
    restart: unless-stopped
    image: emall-cpsimulator-prod:1.0.0
    build:
      context: cpsimulator
      target: production
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - shared-networks

  adminer:
    image: adminer
    container_name: eMall_adminer
    ports:
      - 8080:8080
    networks:
      - shared-networks
    depends_on:
      - postgres

networks:
  shared-networks:
